EkominiB2B.WebUI/Controllers/AnnouncementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EkominiB2B.Business.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace EkominiB2B.WebUI.Controllers
{
    public class AnnouncementController : Controller
    {
        private IAnnouncementService announcementService;

        public AnnouncementController(IAnnouncementService announcementService)
        {
            this.announcementService = announcementService;
        }

        public IActionResult Index()
        {
            var all = announcementService.GetAll("ApplicationUser").ToList();
            return View(all);
        }

        public IActionResult Details(int Id)
        {
            var announcement = announcementService.Get(Id);
            return View(announcement);
        }
    }
}

EkominiB2B.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EkominiB2B.Business.Abstract;
using EkominiB2B.Entities;
using EkominiB2B.Entities.Concrete;
using EkominiB2B.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using Sakura.AspNetCore;

namespace EkominiB2B.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductService productService;
        private ICategoryService categoryService;

        public ProductController(IProductService productService, ICategoryService categoryService)
        {
            this.productService = productService;
            this.categoryService = categoryService;
        }

        public IActionResult Index(double? minPrice, double? maxPrice,string OrderBy, int? categoryId = 0, int page = 1, int PageSize = 12)
        {
          

            var products = productService.GetAll("Category");

            ViewBag.Max = (int)Math.Ceiling(Convert.ToDecimal(products.Max(d=> d.Price - (d.Price * d.DiscountRatio))??0));
            ViewBag.Min = (int)Math.Floor(Convert.ToDecimal(products.Min(d => d.Price - (d.Price * d.DiscountRatio)) ?? 0));

            ViewBag.minPrice = minPrice ?? ViewBag.Min;
            ViewBag.maxPrice = maxPrice ?? ViewBag.Max;
            ViewBag.categoryId = categoryId;
            ViewBag.OrderBy = OrderBy??"default";
            ViewBag.page = page;
            ViewBag.PageSize = PageSize;

 
            ViewBag.ProductCount = products.Count();

            ProdcuctViewModel model = new ProdcuctViewModel();
            model.Categories = categoryService.GetAll().ToList();
            var x = products
                .Where(d => minPrice == null ? true : (d.Price - (d.Price * d.DiscountRatio)) >= minPrice)
                .Where(d => maxPrice == null ? true : (d.Price - (d.Price * d.DiscountRatio)) <= maxPrice)
                .Where(d => categoryId == 0 ? true : d.CategoryId == categoryId);
              //  

            model.Products = Ordering(x, OrderBy).ToPagedList(PageSize, page);

            return View(model);
        }

        private IEnumerable<Product> Ordering(IEnumerable<Product> x, string orderBy)
        {
            if (orderBy=="new")
            {
                return x.OrderByDescending(d => d.UpdatedAt);
            }
            else if (orderBy== "Name")
            {
                return x.OrderBy(d => d.ProductName);
            }
            else if (orderBy == "decrease")
            {
                return x.OrderByDescending(d => (d.Price - (d.Price * d.DiscountRatio)));
            }
            else if (orderBy == "increase")
            {
                return x.OrderBy(d => (d.Price - (d.Price * d.DiscountRatio)));
            }
            else
            {
                return x;
            }

           
        }

        public IActionResult Details(int Id)
        {
            var product = productService.Get(Id);
            return View(product);
        }
    }
}

EkominiB2B.WebUI/Views/Shared/Components/MobileMenu/Default.cshtml
@model IEnumerable<Category>


<div class="mobile-menu-overlay"></div><!-- End .mobil-menu-overlay -->
<div class="mobile-menu-container">
    <div class="mobile-menu-wrapper">
        <span class="mobile-menu-close"><i class="icon-cancel"></i></span>
        <nav class="mobile-nav">
            <ul class="mobile-menu">
                <li class="active"><a href="/"> Anasayfa </a></li>
                <li>
                    <a asp-action="Index" asp-controller="Product"> Kategoriler</a>
                    <ul>
                        @foreach (var item in Model)
                        {
                            <li>
                                <a asp-action="Index" asp-controller="Product" asp-route-categoryId="@item.Id">@item.CategoryName @(item.Id == 1 ? Html.Raw("<span class='tip tip-hot'>Populer!</span>") : Html.Raw(""))</a>
                            </li>

                        }

                    </ul>
                </li>

                <li><a asp-action="Index" asp-controller="Product">Ürünler</a></li>
                <li><a asp-action="About" asp-controller="Home">Hakkımızda</a></li>
                <li><a asp-action="Contact" asp-controller="Home">İletişim</a></li>
                <li><a style="color:#2196f3" asp-action="Campaigns" asp-controller="Home">Kampanyalar <span class="tip tip-new">Hemen Tıkla!</span> </a></li>
                <li><a asp-action="Index" asp-controller="Announcement">Duyurular</a></li>
            </ul>
        </nav><!-- End .mobile-nav -->
        <div class="social-icons">
            <a href="#" class="social-icon" target="_blank"><i class="icon-facebook"></i></a>
            <a href="#" class="social-icon" target="_blank"><i class="icon-twitter"></i></a>
            <a href="#" class="social-icon" target="_blank"><i class="icon-instagram"></i></a>
        </div><!-- End .social-icons -->
    </div><!-- End .mobile-menu-wrapper -->
</div><!-- End .mobile-menu-container -->